Conditionally show backtrace
boutproject/BOUT-dev pull request #1974
Opened 2020-03-19 19:35 UTC by dschwoerer

Read the environment variable BOUT_SHOW_BACKTRACE.
If the variable is set, show the backtrace, otherwise just show the
message.
The allows to get the backtrace without having to attache gdb, or catch
the exception. The default behaviour is not changed.

2020-03-20 00:36 UTC, dschwoerer commented
I was debugging test-communications but it could also be quiet useful for the python interface. I think getenv should be sufficiently portable, otherwise it could be easily wrapped in an ifdef and detected at configure time ...

2020-03-20 09:32 UTC, ZedThree commented on include/boutexception.hxx
> +    if (getenv("BOUT_SHOW_BACKTRACE") != nullptr) {
This is portable, but should be `std::getenv` from `<cstdlib>`

https://en.cppreference.com/w/cpp/utility/program/getenv

2020-03-20 09:43 UTC, ZedThree commented
Neat, thanks!

Could the integrated test be a unit test instead? It turns out `setenv/unsetenv` aren't actually in the standard for some reason :disappointed: but it's possible to write a small wrapper/`#ifdef` something reasonable: https://github.com/googleapis/google-cloud-cpp/issues/100

Also interesting:
https://www.greenend.org.uk/rjk/tech/putenv.html

2020-03-23 19:48 UTC, dschwoerer commented
I am not sure a unit test is much better, as that would always be build, whereas integrated tests can be easily disabled by default. We are spending most time compiling, so I prefer having it separated.

Also `setenv`/`putenv` not being standard is another reason to not put it in a unit test.

2020-03-24 11:46 UTC, ZedThree commented
That is a downside of the unit tests currently, yes. But incremental builds should be pretty fast.

The benefits of having unit tests are having as much stuff as possible in the same framework, which allows easy filtering, reruns, etc, and can really benefit run time.
The other advantage is that stuff in the unit tests gets the coverage run, and means we don't need to come up with some way of working out which integrated tests can be stuck into the coverage run and how to do that in a nice way.

2020-04-01 23:49 UTC, dschwoerer commented
It might be a bit tricky, because we probably want to restore the state afterwards, because that might very well be used to debug failures in the unit tests ...

However, currently it does break the unit tests, if the env var is set -.-

2020-10-28 15:56 UTC, dschwoerer commented
I think in this case it might make sense to keep it outside of the unit-tests.
As `setenv` is not standard, and also might be leaking memory. I am hesitant to put it in the unit tests, as it might cause more issues, and having a separate test doesn't seem that bad to me.

2020-11-02 09:35 UTC, ZedThree commented
Alright, you've convinced me :) This is a useful feature, we'll just have to start adding some integrated tests to the coverage build!

At the moment, this test won't be built for CMake -- might be easier to convert `runtest` to a python script in order to use `run_wrapper.build_and_log`.

2020-11-02 09:39 UTC, ZedThree requested changes

2020-11-02 09:39 UTC, ZedThree commented on manual/sphinx/user_docs/advanced_install.rst
> +`BOUT_SHOW_BACKTRACE` in order for the exception to include the
This one always catches me too, rst needs double backticks:
```suggestion
``BOUT_SHOW_BACKTRACE`` in order for the exception to include the
```

2020-11-02 09:39 UTC, ZedThree commented on tests/integrated/test-backtrace/makefile
> +BOUT_TOP	= ../../..
```suggestion
BOUT_TOP	?= ../../..
```

2020-11-02 09:39 UTC, ZedThree commented on tests/integrated/test-backtrace/runtest
> +make || e=$?
This won't work if using CMake and a non-makefile build generator, so it might be easier to convert this to a python script

2020-12-10 12:02 UTC, ZedThree commented
I've moved the added code from `what()` to the `BoutException` constructor because it was returning a pointer to a temporary and so didn't work. Because `what()` is `const` and needs to return `const char*`, we need to have made the message already -- the only place to do this is the constructor.

I also converted the `runtest` to Python, so now it works when using CMake + Ninja.

2020-12-10 12:02 UTC, ZedThree approved these changes

2020-12-10 13:00 UTC, ZedThree commented
@dschwoerer Look ok to you? Still works for your use case?

2020-12-28 12:00 UTC, merged