Faster recompile
boutproject/BOUT-dev pull request #2294
Opened 2021-04-28 10:43 UTC by dschwoerer

Especially nice if working with shared libraries, and only a single, small file needs to be recompiled.

Recompiling `bout++.cxx` can take a long time, and this issue issue is avoided this way.

Due to #1933 not useful for cmake ...

I accidentally included 73e7ad8 - but that might be useful anyway to avoid a regression?

2021-04-30 13:53 UTC, ZedThree requested changes
Nice, thanks @dschwoerer ! One small change please :)

2021-04-30 13:53 UTC, ZedThree commented on src/bout++.cxx
> +  output_progress.write(_("Code compiled on {:s} at {:s}\n\n"), boutcompiletime, boutcompiledate);
Typo:

```suggestion
  output_progress.write(_("Code compiled on {:s} at {:s}\n\n"), boutcompiledate, boutcompiletime);
```

2021-04-30 13:54 UTC, ZedThree commented
The black test is failing because it's trying to run on everything and two files are not compatible with python 3.

2021-05-01 18:56 UTC, dschwoerer commented
> The black test is failing because it's trying to run on everything and two files are not compatible with python 3.

I am confused why it is trying to do that now. Shouldn't black already be running on next?
I further thought that this has already succeded, where the files reintroduced accidentially?

2021-05-04 15:16 UTC, ZedThree commented
black is failing on this file: https://github.com/boutproject/BOUT-dev/blob/d2750d5cd3fa7b17b75ffbc9001c9163839a2967/tools/tokamak_grids/pyGridGen/aeqdsk.py

which no longer exists in `next`. I think this is just because this branch was off an old version of `next`. I suggest merging in latest `next`

2021-05-04 15:36 UTC, dschwoerer commented
It seems I forgot to fetch before merging next. Thanks for the catch, it now works :+1:

2021-05-04 16:15 UTC, ZedThree approved these changes

2021-05-04 16:16 UTC, merged