Update outer boundaries in PETSc 3D solver
boutproject/BOUT-dev pull request #2496
Opened 2022-02-14 19:26 UTC by bendudson

Only affects boundary conditions if MXG > 1: First set of boundary cells are already set as part of the solve.

Changes from always zero-gradient to extrapolating. If zero-gradient boundary conditions are set then the result will not change.

2022-02-16 14:32 UTC, johnomotani requested changes
Thanks @bendudson! This looks totally general, and consistent with `boundary_standard.cxx` (with suggestions below). Nice how simple it is!

2022-02-16 14:32 UTC, johnomotani commented on src/invert/laplace/impls/petsc3damg/petsc3damg.cxx
> +      solution[i.xm(b)] = 2.*solution[i.xm(b-1)] - solution[i.xm(b-2)];
To be consistent with the extrapolation in the boundary conditions, e.g. here (after rearranging to replace `delta * val` with values of `f` from the previous line)
https://github.com/boutproject/BOUT-dev/blob/ca49afe984ee93203ce0709d30c9219bbde17a68/src/mesh/boundary_standard.cxx#L2138-L2143
I think we need higher order extrapolation:
```suggestion
      solution[i.xm(b)] = 3.*solution[i.xm(b-1)] - 3.*solution[i.xm(b-2)] + solution[i.xm(b-3)];
```

2022-02-16 14:32 UTC, johnomotani commented on src/invert/laplace/impls/petsc3damg/petsc3damg.cxx
> +      solution[i.xp(b)] = 2.*solution[i.xp(b-1)] - solution[i.xp(b-2)];
see above
```suggestion
      solution[i.xp(b)] = 3.*solution[i.xp(b-1)] - 3.*solution[i.xp(b-2)] + solution[i.xp(b-3)];
```

2022-02-16 14:43 UTC, ZedThree commented
Is this one of things that can only be effectively tested with MMS?

2022-04-27 17:36 UTC, johnomotani approved these changes
Looks good to me!

2022-04-27 17:36 UTC, merged