rename FV::Div_a_Grad_perp
boutproject/BOUT-dev pull request #2536
Opened 2022-04-25 20:49 UTC by dschwoerer

This operator is calculating the Divergence of the Gradient (i.e.
Laplace), not the Divergence of the Laplacian.

Should this be called `Div_perp_a_Grad_perp` or even `Div_perp_K_Grad_perp` (similar to the parallel version)?

2022-04-25 20:51 UTC, bendudson approved these changes
Thanks @dschwoerer I agree the new name is better

2022-04-26 08:38 UTC, ZedThree requested changes
LGTM, thanks for the nice deprecation notice too!

2022-04-26 08:38 UTC, ZedThree commented on include/bout/fv_ops.hxx
> +const Field3D Div_a_Grad_perp(const Field3D& a, const Field3D& x);
If we're touching this, let's drop `const` at the same time:

```suggestion
Field3D Div_a_Grad_perp(const Field3D& a, const Field3D& x);
```

2022-04-26 08:38 UTC, ZedThree commented on include/bout/fv_ops.hxx
> +[[deprecated("Please use Div_a_Grad_perp instead")]] inline const Field3D
```suggestion
[[deprecated("Please use Div_a_Grad_perp instead")]] inline Field3D
```

2022-04-26 08:38 UTC, ZedThree commented on src/mesh/fv_ops.cxx
> +const Field3D Div_a_Grad_perp(const Field3D& a, const Field3D& f) {
```suggestion
Field3D Div_a_Grad_perp(const Field3D& a, const Field3D& f) {
```

2022-04-26 08:54 UTC, ZedThree approved these changes

2022-04-29 15:45 UTC, ZedThree commented
Failing test is clang-tidy-review which is fixed in both master/next

2022-04-29 15:46 UTC, merged

2022-05-02 07:10 UTC, dschwoerer commented
Does the title contain `FV::Div_a_Grad_perp` twice? Old name was `FV::Div_a_Laplace_perp` - sorry for not providing a better title.

2022-05-03 08:58 UTC, ZedThree commented
Oops, sorry, I clearly didn't read things properly! I'll just have to remember to fix it for the changelog