switch to BOUT_FOR and simplify Div_a_Grad_perp
boutproject/BOUT-dev pull request #2641
Opened 2023-02-07 14:34 UTC by dschwoerer

2023-02-22 12:04 UTC, ZedThree requested changes

2023-02-22 12:04 UTC, ZedThree commented on src/mesh/fv_ops.cxx
> +#define GET(fci, a, b)                              \
This is a really nice simplification of the logic in this function, but please don't use macros unless absolutely necessary. Here's an implementation using a struct for example:

```cpp
  struct Slices {
    Field3D c;
    Field3D up;
    Field3D down;
    Slices(bool use_slices, const Field3D& field) : 
      c(use_slices ? field : toFieldAligned(field)),
      up(use_slices ? field.yup() : c),
      down(use_slices ? field.ydown() : c) {}
  };

  const Slices f_slices{fci, f};
  const Slices a_slices{fci, a};
```

2023-02-22 14:38 UTC, dschwoerer commented on src/mesh/fv_ops.cxx
> +#define GET(fci, a, b)                              \
Thanks, that's really neat :+1:

2023-02-23 11:06 UTC, dschwoerer commented on src/mesh/fv_ops.cxx
> +template <class Field3D>
Yes, otherwise dx and so may be converted to `Field3D` in case of 2D metrics.

I changed it to `T` :+1:

2023-02-23 17:32 UTC, ZedThree commented on src/mesh/fv_ops.cxx
> +}
Just to note that we'll upgrade to C++17 soon and that should be able to deduce `T` without this helper

2023-02-23 17:32 UTC, ZedThree approved these changes

2023-02-23 17:32 UTC, merged