Remove `backtrace` example, move into docs instead
boutproject/BOUT-dev pull request #2842
Opened 2024-01-22 14:01 UTC by ZedThree

- Add a new docs page to summarise debugging utilities: `output_debug`, `TRACE`, and the exception backtrace
- Remove the `backtrace` example

2024-01-22 15:34 UTC, dschwoerer requested changes

2024-01-22 15:34 UTC, dschwoerer commented on manual/sphinx/developer_docs/debugging.rst
> +(``-DBOUT_ENABLE_BACKTRACE=on``, the default, requires the
```suggestion
(``-DBOUT_ENABLE_BACKTRACE=ON``, the default, requires the
```

2024-01-22 15:34 UTC, dschwoerer commented on manual/sphinx/developer_docs/debugging.rst
> +_and_ the physics model.
```suggestion
_and_ the physics model. If debug symbols are only present in part, the
backtrace will be missing names for the other part.
```

2024-01-22 15:34 UTC, dschwoerer commented on manual/sphinx/developer_docs/debugging.rst
> +This output tends to be much less user-friendly than the message stack
```suggestion
This output tends to be much harder to read than the message stack
```

I find it much friendlier to get in most cases all the info I need without changing the code :-)

2024-01-22 15:34 UTC, dschwoerer commented on manual/sphinx/user_docs/physics_models.rst
> +configure BOUT++ with ``-DENABLE_OUTPUT_DEBUG``. When running BOUT++
```suggestion
configure BOUT++ with ``-DBOUT_ENABLE_OUTPUT_DEBUG=ON``. When running BOUT++
```

2024-01-22 15:34 UTC, dschwoerer commented on manual/sphinx/user_docs/physics_models.rst
> +``-q -q`` suppresses everything except ``output_warn`` and
` output_progress` is disabled here, in case someone wonders like me ...

2024-02-08 00:30 UTC, bendudson approved these changes

2024-02-14 08:57 UTC, merged