Merge v5.1.1 into `next`
boutproject/BOUT-dev pull request #2978
Opened 2024-09-18 15:46 UTC by ZedThree

There were quite a lot of conflicts in the SUNDIALS solvers, so this definitely needs double-checking

2024-10-21 11:46 UTC, dschwoerer requested changes
I am worried that the CI did not catch the `n`.
Can we rerun the CI?

2024-10-21 11:46 UTC, dschwoerer commented on CHANGELOG.md
> +- Add fallback if the version has been bumped bot not tagged [\#2754][https://github.com/boutproject/BOUT-dev/pull/2754] ([dschwoerer][https://github.com/dschwoerer])
```suggestion
- Add fallback if the version has been bumped but not tagged [\#2754][https://github.com/boutproject/BOUT-dev/pull/2754] ([dschwoerer][https://github.com/dschwoerer])
```

2024-10-21 11:46 UTC, dschwoerer commented on CITATION.cff
>  date-released: 2023-04-10
that should be updated?

2024-10-21 11:46 UTC, dschwoerer commented on locale/de/libbout.po
>  msgstr ""
We probably should remove empty translations?

2024-10-21 11:46 UTC, dschwoerer commented on src/solver/impls/cvode/cvode.cxx
> +n/**************************************************************************
```suggestion
/**************************************************************************
```

CI should have caught this one!

2024-10-23 16:07 UTC, ZedThree commented
@Steven-Roberts Would you be able to double-check the SUNDIALS parts have been resolved correctly please?

2024-10-24 17:18 UTC, Steven-Roberts commented
I can take a look early next week

2024-10-30 23:33 UTC, Steven-Roberts commented
@ZedThree The SUNDIALS-related changes look fine. I confirmed that it compiles and an example can run using SUNDIALS version 4, 5, 6, and 7.

2024-10-31 16:03 UTC, merged

2024-10-31 16:04 UTC, bendudson commented
Thanks @Steven-Roberts for checking the SUNDIALS changes!