Fix Field3D::setBoundaryTo for FCI methods
boutproject/BOUT-dev pull request #3030
Opened 2024-11-21 23:17 UTC by bendudson

Without this fix, boundary conditions set on yup/down fields are not applied when a boundary is copied from one field to another.

@dschwoerer This is needed in Hermes-3 with FCI so that this line correctly applies the sheath boundary conditions to the density field:
https://github.com/bendudson/hermes-3/blob/master/src/evolve_density.cxx#L217

2024-11-22 06:59 UTC, dschwoerer requested changes

2024-11-22 06:59 UTC, dschwoerer commented on src/field/field3d.cxx
> +        pnt.dirichlet_o2(*this, val);
We should either take o2 twice, or o1 twice:
```suggestion
        pnt.dirichlet_o1(*this, val);
```

I think `o1` should be sufficient, as `f3d` and `*this` should be close. But I am not sure what is more stable ...

2024-11-22 06:59 UTC, dschwoerer commented on src/field/field3d.cxx
> +    return;
For hermes that might work, but should we not also copy the x-boundary conditions with FCI?
```suggestion
```

2024-11-25 15:48 UTC, dschwoerer commented on src/field/field3d.cxx
> +        pnt.dirichlet_o2(*this, val);
The FA code also uses first order, so I have pushed a fixed based on that ...

2024-11-26 09:09 UTC, dschwoerer commented
@bendudson Are you ok with these changes?

2024-11-26 16:25 UTC, dschwoerer commented
I just noticed #2962 is also open - is the other still needed with this one?

2024-11-26 16:27 UTC, bendudson reviewed
Thanks @dschwoerer ! The changes look good to me.
I think #2962 is not needed once this is merged.

2024-11-27 07:48 UTC, dschwoerer approved these changes

2024-11-27 07:48 UTC, merged