Dry up examples
boutproject/BOUT-dev pull request #3046
Opened 2024-12-16 19:54 UTC by tomc271

Extracted duplicated code to new class TokamakCoordinates that makes a Coordinates object for a tokamak system.

2025-01-29 14:35 UTC, ZedThree commented on include/bout/tokamak_coordinates.hxx
> +        ShearFactor *= Lbar * Lbar * Bbar * ShearFactor;
```suggestion
    FieldMetric I;
    FieldMetric dx;

    TokamakOptions(Mesh& mesh) {
        mesh.get(Rxy, "Rxy");
        //    mesh->get(Zxy, "Zxy");
        mesh.get(Bpxy, "Bpxy");
        mesh.get(Btxy, "Btxy");
        mesh.get(Bxy, "Bxy");
        mesh.get(hthe, "hthe");
        mesh.get(I, "sinty");
        mesh.get(dx, "dpsi");
    }

    void normalise(BoutReal Lbar, BoutReal Bbar, BoutReal ShearFactor) {
        Rxy /= Lbar;
        Bpxy /= Bbar;
        Btxy /= Bbar;
        Bxy /= Bbar;
        hthe /= Lbar;
        I *= Lbar * Lbar * Bbar * ShearFactor;
```

2025-01-29 14:35 UTC, ZedThree commented on include/bout/tokamak_coordinates.hxx
> +                                     BoutReal Bbar, BoutReal ShearFactor = 1.0) {
We can replace `noshear` completely:

```suggestion
void set_tokamak_coordinates_on_mesh(TokamakOptions& tokamak_options, Mesh& mesh, BoutReal Lbar,
                                     BoutReal Bbar, BoutReal ShearFactor = 0.0) {
```

2025-01-31 10:22 UTC, dschwoerer requested changes
Looks good, but can probably be further polished.

2025-01-31 10:22 UTC, dschwoerer commented on tests/integrated/test-laplacexy/loadmetric.cxx
> +  bool noshear;
`noshear` is in an undefined state

2025-01-31 10:22 UTC, dschwoerer commented on tests/integrated/test-drift-instability/2fluid.cxx
> +      noshear = true;
`noshear` could be replaced by `ShiftXderivs`

2025-02-19 15:29 UTC, ZedThree requested changes

2025-02-19 15:29 UTC, ZedThree commented on examples/6field-simple/elm_6f.cxx
> +      noshear = true;
```suggestion
```

2025-02-21 15:52 UTC, ZedThree commented on include/bout/tokamak_coordinates.hxx
> +            dx = mesh.getCoordinates().dx();
`getCoordinates()` returns a pointer:
```suggestion
            dx = mesh.getCoordinates()->dx();
```

2026-04-24 09:20 UTC, closed without merging